In [1]:
import pandas as pd
import datetime as dt
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns

In [8]:
df = pd.read_excel(open('/content/retail.xlsx', 'rb'))
df.sample(5)

                              Id              Date  ... Adjustment StockAfter
184422  61f40f2347eb85ada9f55d14  28.01.2022 01:20  ...     -0.086    13.6331
110370  61e6b2a55192a4f1d7c5e5ea  18.01.2022 01:17  ...     -1.000   189.0000
159518  61efd95f293bb17692435853  25.01.2022 01:16  ...     20.000   -10.0000
153538  61ee97161d399e70bbd89efd  24.01.2022 01:17  ...   -375.000   694.0000
21555   61d718e4255f650dc3db81b6  06.01.2022 01:21  ...     -4.000    10.0000

[5 rows x 7 columns]

In [9]:
df.shape # data frame hajmi

(220144, 7)

In [10]:
nulls = df.isnull().sum() # null qiymatlar soni
nulls

Id            0
Date          0
Item          0
Employee      0
Reason        0
Adjustment    0
StockAfter    0
dtype: int64

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 220144 entries, 0 to 220143
Data columns (total 7 columns):
 #   Column      Non-Null Count   Dtype
---  ------      --------------   -----
 0   Id          220144 non-null  object
 1   Date        220144 non-null  object
 2   Item        220144 non-null  object
 3   Employee    220144 non-null  object
 4   Reason      220144 non-null  object
 5   Adjustment  220144 non-null  float64
 6   StockAfter  220144 non-null  float64
dtypes: float64(2), object(5)
memory usage: 11.8+ MB

In [12]:
df.describe()

          Adjustment     StockAfter
count  220144.000000  220144.000000
mean        0.947031    6252.026721
std       270.697203   24009.606184
min    -12000.000000   -5323.000000
25%        -2.000000      10.000000
50%        -1.000000      46.000000
75%        -1.000000     260.000000
max    100521.000000  154475.000000

In [13]:
df.duplicated().sum() # takrorlangan qiymatlar soni

0

In [14]:
df['Id'].value_counts() # Id lar turlicha ekan. Ularning bizga keragi yo'q

61cf6c1a84e3ba0f3e8509c2    1
61ed4c1bb7fd2210a60eeb7a    1
61ed4c1bb7fd2210a60eeb80    1
61ed4c1bb7fd2210a60eeb79    1
61ed4c1bb7fd2210a60eeb77    1
                           ..
61e0556ceb0772ab10250a57    1
61e0556ceb0772ab10250a55    1
61e0556ceb0772ab10250a5e    1
61e0556ceb0772ab10250a59    1
61f981ea1b75e6e6b86211c5    1
Name: Id, Length: 220144, dtype: int64

In [15]:
df.drop('Id', axis=1, inplace=True)

In [16]:
df = df[df['Reason']=='sold'] # faqat sotilgan mahsulotlar ro'yhatini olish

In [17]:
df.drop('Employee', axis=1, inplace=True) # Employee ustuni kerakmas. Uni tashlab yuboramiz

In [18]:
df['Vaqt'] = df['Date'].map(lambda x: x[0:10])
df.drop('Date', axis=1, inplace=True)

In [19]:
df['Date'] = df['Vaqt']
df.drop('Vaqt', axis=1, inplace=True)

In [20]:
df['Date'] = pd.to_datetime(df['Date'], format="%d.%m.%Y") # Date ustunini datetime formatiga o'tkazish

In [21]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 208552 entries, 0 to 220143
Data columns (total 5 columns):
 #   Column      Non-Null Count   Dtype
---  ------      --------------   -----
 0   Item        208552 non-null  object
 1   Reason      208552 non-null  object
 2   Adjustment  208552 non-null  float64
 3   StockAfter  208552 non-null  float64
 4   Date        208552 non-null  datetime64[ns]
dtypes: datetime64[ns](1), float64(2), object(2)
memory usage: 9.5+ MB

In [22]:
df['Item'].value_counts() # 11337 xil mahsulot bir ekan

Paket Tiin 10kg                                                                     12718
Буханка обычная шт                                                                   2249
Банан вес                                                                            1854
Хлеб Патир Чигатой 1шт                                                               1469
Напиток Coca-Cola п/б 1.5л                                                           1367
                                                                                    ...
Stremyanka class plus 3 stupenchataya                                                   1
Biskvit konfeti vafelnie na fruktoze 800gr                                              1
Eco Zamon Tovuq butun kg                                                                1
Ulker Koncerto milk chocolate with crisped rice and hazelnut cream filling 500gr        1
HiPP Фруктовое пюре Груша-Банан-Яблоко Hippis 100гр                                     1
Name: Item, Length: 11337, dtype: int64

In [23]:
df = df.groupby(by=['Item']).mean()
df   # df ni Item ustuni boyicha ortacha qiymatini topish

                                                    Adjustment   StockAfter
Item
"Икринка" Икра деликатесная с креветкой 160 гр       -1.000000     6.500000
"Роллтон" КИМЧИ 90г                                  -1.500000    96.750000
"САНТА БРЕМОР" Палочка крабовые замороженное 10...   -2.000000     6.000000
*kc127* fourlınes double sıde jar 500ml              -2.000000    18.000000
1 Gold shokolad sht (kassa)                          -3.250000   922.267857
...                                                        ...          ...
картофель фри застолье 1 кг                          -1.000000     1.000000
мак. "РОЛЛТОН" UZ со вкусом говядины 60гр            -2.764706  1933.176471
молочный шоколад джандуйотто и фундук джандуйя ...   -1.000000     4.000000
набор для выпечки 8 м                                -1.000000     3.500000
свекла с яблоком                                     -0.589775     0.386150

[11337 rows x 2 columns]

In [24]:
df.drop('StockAfter', axis=1, inplace=True) # StockAfter ustuni kerakmas. Uni tashlab yuboramiz

In [25]:
df['Result'] = df['Adjustment'].map(lambda x: np.abs(3*x)) # Result ustunini qo'shish

In [26]:
df

                                                    Adjustment    Result
Item
"Икринка" Икра деликатесная с креветкой 160 гр       -1.000000  3.000000
"Роллтон" КИМЧИ 90г                                  -1.500000  4.500000
"САНТА БРЕМОР" Палочка крабовые замороженное 10...   -2.000000  6.000000
*kc127* fourlınes double sıde jar 500ml              -2.000000  6.000000
1 Gold shokolad sht (kassa)                          -3.250000  9.750000
...                                                        ...       ...
картофель фри застолье 1 кг                          -1.000000  3.000000
мак. "РОЛЛТОН" UZ со вкусом говядины 60гр            -2.764706  8.294118
молочный шоколад джандуйотто и фундук джандуйя ...   -1.000000  3.000000
набор для выпечки 8 м                                -1.000000  3.000000
свекла с яблоком                                     -0.589775  1.769325

[11337 rows x 2 columns]

In [27]:
df_result = df.drop('Adjustment', axis=1)
df_result

                                                      Result
Item
"Икринка" Икра деликатесная с креветкой 160 гр      3.000000
"Роллтон" КИМЧИ 90г                                 4.500000
"САНТА БРЕМОР" Палочка крабовые замороженное 10...  6.000000
*kc127* fourlınes double sıde jar 500ml             6.000000
1 Gold shokolad sht (kassa)                         9.750000
...                                                      ...
картофель фри застолье 1 кг                         3.000000
мак. "РОЛЛТОН" UZ со вкусом говядины 60гр           8.294118
молочный шоколад джандуйотто и фундук джандуйя ...  3.000000
набор для выпечки 8 м                               3.000000
свекла с яблоком                                    1.769325

[11337 rows x 1 columns]

In [28]:
df_main = pd.read_excel(open('/content/retail.xlsx', 'rb'))
df_main

                              Id              Date  ... Adjustment  StockAfter
0       61cf6c1a84e3ba0f3e8509c2  01.01.2022 01:01  ...       -1.0  18900.0000
1       61cf6c1a84e3ba0f3e8509c1  01.01.2022 01:01  ...       -1.0     21.0000
2       61cf6c1a84e3ba0f3e8509c3  01.01.2022 01:01  ...       -1.0    886.0000
3       61cf6c1a84e3ba0f3e8509bf  01.01.2022 01:01  ...       -1.0   -289.0000
4       61cf6c8984e3ba0f3e8509de  01.01.2022 01:01  ...      -19.5   -693.7155
...                          ...               ...  ...        ...         ...
220139  61f981ea1b75e6e6b86211c8  01.02.2022 02:23  ...       -1.0     20.0000
220140  61f981ea1b75e6e6b86211c6  01.02.2022 02:23  ...       -1.0      5.0000
220141  61f981ea1b75e6e6b86211c7  01.02.2022 02:23  ...       -1.0      4.0000
220142  61f981ea1b75e6e6b86211c9  01.02.2022 02:23  ...       -1.0      6.0000
220143  61f981ea1b75e6e6b86211c5  01.02.2022 02:23  ...       -1.0      5.0000

[220144 rows x 7 columns]

In [29]:
df_main.drop(['Id', 'Employee', 'Reason', 'Adjustment'], axis=1, inplace=True)

In [32]:
df_main['Vaqt'] = df_main['Date'].map(lambda x: x[0:10])
df_main.drop('Date', axis=1, inplace=True)

In [33]:
df_main['Date'] = df_main['Vaqt']
df_main.drop('Vaqt', axis=1, inplace=True)

In [34]:
df_main['Date'] = pd.to_datetime(df_main['Date'], format="%d.%m.%Y") # Date ustunini datetime formatiga o'tkazish

In [35]:
df_main.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 220144 entries, 0 to 220143
Data columns (total 3 columns):
 #   Column      Non-Null Count   Dtype
---  ------      --------------   -----
 0   Item        220144 non-null  object
 1   StockAfter  220144 non-null  float64
 2   Date        220144 non-null  datetime64[ns]
dtypes: datetime64[ns](1), float64(1), object(1)
memory usage: 5.0+ MB

In [36]:
df_main

                                                     Item  ...       Date
0                             Elma vlajnaya salfetka 1sht  ... 2022-01-01
1                Катык Доброе деревенское утро 3.2% 900гр  ... 2022-01-01
2               Коктейль Nesquik со вкусом Шоколада 200мл  ... 2022-01-01
3                     Сокосодержащий Pulpy Апельсин 900мл  ... 2022-01-01
4                                               Банан вес  ... 2022-01-01
...                                                   ...  ...        ...
220139                            Ватные Диски Lady 175шт  ... 2022-02-01
220140  Влажные салфетки Huggies Ultra Comfort с Алоэ ...  ... 2022-02-01
220141  Молочная Смесь Nutrilak Premium 4 с 18 мес. 600гр  ... 2022-02-01
220142  Подгузник-Трусики Huggies Pants 6 для девочек ...  ... 2022-02-01
220143           Прокладки Bella Perfecta Ultra Blue 10шт  ... 2022-02-01

[220144 rows x 3 columns]

In [41]:
df_main = df_main[df_main['Date']=='2022-02-01']

In [42]:
df_main

                                                     Item  ...       Date
211654                              Mandarin kg Pokiston.  ... 2022-02-01
211655                              Olma Golden kg otbor.  ... 2022-02-01
211656                      Cream cheese 250gr slivochniy  ... 2022-02-01
211657                Cливочное масло President 82% 200гр  ... 2022-02-01
211658                           Friskies 85gr s indeykoy  ... 2022-02-01
...                                                   ...  ...        ...
220139                            Ватные Диски Lady 175шт  ... 2022-02-01
220140  Влажные салфетки Huggies Ultra Comfort с Алоэ ...  ... 2022-02-01
220141  Молочная Смесь Nutrilak Premium 4 с 18 мес. 600гр  ... 2022-02-01
220142  Подгузник-Трусики Huggies Pants 6 для девочек ...  ... 2022-02-01
220143           Прокладки Bella Perfecta Ultra Blue 10шт  ... 2022-02-01

[8490 rows x 3 columns]

In [43]:
df_main.drop('Date', axis=1, inplace=True)

/usr/local/lib/python3.7/dist-packages/pandas/core/frame.py:4913: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  errors=errors,

In [44]:
df_main

                                                     Item  StockAfter
211654                              Mandarin kg Pokiston.     13.6182
211655                              Olma Golden kg otbor.     17.6361
211656                      Cream cheese 250gr slivochniy      5.0000
211657                Cливочное масло President 82% 200гр    435.0000
211658                           Friskies 85gr s indeykoy    120.0000
...                                                   ...         ...
220139                            Ватные Диски Lady 175шт     20.0000
220140  Влажные салфетки Huggies Ultra Comfort с Алоэ ...      5.0000
220141  Молочная Смесь Nutrilak Premium 4 с 18 мес. 600гр      4.0000
220142  Подгузник-Трусики Huggies Pants 6 для девочек ...      6.0000
220143           Прокладки Bella Perfecta Ultra Blue 10шт      5.0000

[8490 rows x 2 columns]

In [45]:
df_result

                                                      Result
Item
"Икринка" Икра деликатесная с креветкой 160 гр      3.000000
"Роллтон" КИМЧИ 90г                                 4.500000
"САНТА БРЕМОР" Палочка крабовые замороженное 10...  6.000000
*kc127* fourlınes double sıde jar 500ml             6.000000
1 Gold shokolad sht (kassa)                         9.750000
...                                                      ...
картофель фри застолье 1 кг                         3.000000
мак. "РОЛЛТОН" UZ со вкусом говядины 60гр           8.294118
молочный шоколад джандуйотто и фундук джандуйя ...  3.000000
набор для выпечки 8 м                               3.000000
свекла с яблоком                                    1.769325

[11337 rows x 1 columns]

In [57]:
df_mcopy = df_main.copy()

In [60]:
df_mcopy.set_index('Item', inplace=True)

In [61]:
df_mcopy['Result'] = df_result['Result']

In [62]:
df_mcopy

                                                    StockAfter    Result
Item
Mandarin kg Pokiston.                                  13.6182  3.215219
Olma Golden kg otbor.                                  17.6361  5.561163
Cream cheese 250gr slivochniy                           5.0000  3.000000
Cливочное масло President 82% 200гр                   435.0000  3.697183
Friskies 85gr s indeykoy                              120.0000  6.250000
...                                                        ...       ...
Ватные Диски Lady 175шт                                20.0000  3.750000
Влажные салфетки Huggies Ultra Comfort с Алоэ 56шт      5.0000  3.972973
Молочная Смесь Nutrilak Premium 4 с 18 мес. 600гр       4.0000  6.000000
Подгузник-Трусики Huggies Pants 6 для девочек (...      6.0000  4.500000
Прокладки Bella Perfecta Ultra Blue 10шт                5.0000  3.272727

[8490 rows x 2 columns]

In [65]:
df_mcopy['Final Result'] = np.where(df_mcopy['StockAfter'] < df_mcopy['Result'], df_mcopy['StockAfter'], np.nan)

In [66]:
df_mcopy

                                                    StockAfter  ...  Final Result
Item                                                            ...
Mandarin kg Pokiston.                                  13.6182  ...           NaN
Olma Golden kg otbor.                                  17.6361  ...           NaN
Cream cheese 250gr slivochniy                           5.0000  ...           NaN
Cливочное масло President 82% 200гр                   435.0000  ...           NaN
Friskies 85gr s indeykoy                              120.0000  ...           NaN
...                                                        ...  ...           ...
Ватные Диски Lady 175шт                                20.0000  ...           NaN
Влажные салфетки Huggies Ultra Comfort с Алоэ 56шт      5.0000  ...           NaN
Молочная Смесь Nutrilak Premium 4 с 18 мес. 600гр       4.0000  ...           4.0
Подгузник-Трусики Huggies Pants 6 для девочек (...      6.0000  ...           NaN
Прокладки Bella Perfecta Ultra Blue 10шт                5.0000  ...           NaN

[8490 rows x 3 columns]

In [72]:
df_final = df_mcopy.dropna()
df_final

                                                   StockAfter  ...  Final Result
Item                                                           ...
King of baking baget fransuzskiy 320gr bol            -7.0000  ...       -7.0000
King of baking bulochki 180gr sdobnie                 -2.0000  ...       -2.0000
Whiskas jele s kurisey 85gr                          -23.0000  ...      -23.0000
Kartoshka kg KZ. Gala Yirik.                       -4931.8208  ...    -4931.8208
Kimchi karam kg Chimchi karam kg                       3.0086  ...        3.0086
...                                                       ...  ...           ...
Подгузники Huggies Classic 5 Mega (11-25 кг) 1шт      -6.0000  ...       -6.0000
Туалетная бумага ракушка Jasmin 6шт                  -12.0000  ...      -12.0000
Elma Детские влажные салфетки BabyLux 72шт             3.0000  ...        3.0000
Стиральный порошок Tide Автомат Color 1.5кг            1.0000  ...        1.0000
Молочная Смесь Nutrilak Premium 4 с 18 мес. 600гр      4.0000  ...        4.0000

[1356 rows x 3 columns]

In [74]:
df_final.drop(['StockAfter', 'Result'], axis=1, inplace=True)

/usr/local/lib/python3.7/dist-packages/pandas/core/frame.py:4913: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  errors=errors,

In [75]:
df_final

                                                   Final Result
Item
King of baking baget fransuzskiy 320gr bol              -7.0000
King of baking bulochki 180gr sdobnie                   -2.0000
Whiskas jele s kurisey 85gr                            -23.0000
Kartoshka kg KZ. Gala Yirik.                         -4931.8208
Kimchi karam kg Chimchi karam kg                         3.0086
...                                                         ...
Подгузники Huggies Classic 5 Mega (11-25 кг) 1шт        -6.0000
Туалетная бумага ракушка Jasmin 6шт                    -12.0000
Elma Детские влажные салфетки BabyLux 72шт               3.0000
Стиральный порошок Tide Автомат Color 1.5кг              1.0000
Молочная Смесь Nutrilak Premium 4 с 18 мес. 600гр        4.0000

[1356 rows x 1 columns]